spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS sc
  jpa:
    properties:
      hibernate:
        #        dialect: com.github.evgeniymelnikov.cache.hibernate.config.H2DialectCustom
        format_sql: true
        generate_statistics: true
        javax.cache:
#            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: 'file:src/main/resources/ehcache.xml'
        cache:
          use_second_level_cache: true
          region.factory_class: jcache
          use_query_cache: true
        hbm2ddl:
          auto: create
    open-in-view: false
logging.level:
  ru.parma.dib: trace
  org.hibernate:
    SQL: trace
    cache: trace
    type.descriptor.sql.BasicBinder: trace
